import Foundation

/// A type that can be extracted from unstructured documents via an LLM.
///
/// Conformances are generated by the ``Extractable()`` macro. Do not implement
/// this protocol manually unless you need a hand-written schema.
///
/// ## Cross-field invariants
///
/// Override ``validateInvariants()`` to declare semantic constraints that cannot be
/// expressed in the JSON Schema alone (e.g. line items + tax ≈ total). A violation is
/// treated like a decode failure: the structured issue is fed back to the model and the
/// extraction retries. When retries are exhausted the call throws
/// ``ExtractionError/validationFailed(attempts:lastError:rawOutput:)``.
///
/// **Useful consequence:** if a type declares invariants and you received a value back,
/// those invariants held on that value. That is arithmetic, not inference — unlike
/// ``ExtractionSignals``, which are only grounding evidence.
public protocol Extractable: Codable, Sendable {
    /// JSON-Schema-like description of this type used for prompting and validation.
    nonisolated static var extractionSchema: ExtractionSchema { get }

    /// Check cross-field semantic invariants after a successful decode.
    ///
    /// Throw ``InvariantValidationError`` with field-addressable issues so the repair
    /// prompt can describe exactly which field failed and what was expected. The default
    /// implementation is a no-op, so existing types and macro-generated conformances
    /// compile without changes.
    func validateInvariants() throws
}

extension Extractable {
    /// Default: no cross-field checks.
    public func validateInvariants() throws {}
}

// MARK: - Invariant issues

/// A single cross-field invariant violation, addressable by field path.
///
/// Paths use the same dotted / indexed style as grounding signals (`total`,
/// `items[0].price`, `expiryDate`) so the repair prompt can name the broken field.
public struct InvariantIssue: Sendable, Equatable, CustomStringConvertible {
    /// Dotted path of the field that failed the check, e.g. `total` or `expiryDate`.
    public let path: String
    /// Human-readable description of the expected relationship or value.
    public let expected: String
    /// What was actually found on the decoded value.
    public let found: String

    /// - Parameters:
    ///   - path: Field path the model should correct (e.g. `total`).
    ///   - expected: What the invariant required (e.g. `items sum + tax ≈ 12.50`).
    ///   - found: The value or relationship that was present instead.
    public init(path: String, expected: String, found: String) {
        self.path = path
        self.expected = expected
        self.found = found
    }

    public var description: String {
        "field `\(path)`: invariant violated — expected \(expected), found \(found)"
    }
}

/// Thrown from ``Extractable/validateInvariants()`` when one or more semantic checks fail.
///
/// The extraction loop formats these issues the same way it formats ``DecodingError``
/// cases, so the model sees a machine-readable field complaint and can repair the JSON.
public struct InvariantValidationError: Error, Sendable, LocalizedError, Equatable {
    /// All issues discovered in a single validation pass (may be more than one).
    public let issues: [InvariantIssue]

    /// - Parameter issues: Non-empty list of field-level violations. An empty list is
    ///   allowed for convenience but will not produce a useful repair prompt.
    public init(issues: [InvariantIssue]) {
        self.issues = issues
    }

    /// Convenience for a single field violation.
    public init(path: String, expected: String, found: String) {
        self.issues = [InvariantIssue(path: path, expected: expected, found: found)]
    }

    public var errorDescription: String? {
        if issues.isEmpty {
            return "Invariant validation failed."
        }
        return issues.map(\.description).joined(separator: "\n")
    }
}

// MARK: - Money comparison

extension Decimal {
    /// Default absolute tolerance for money-like amount comparisons (one cent for
    /// two-decimal currencies). Callers may pass any other value to
    /// ``isApproximatelyEqual(to:tolerance:)``.
    public static let defaultMoneyTolerance = Decimal(sign: .plus, exponent: -2, significand: 1)

    /// Compare amounts with an explicit absolute tolerance.
    ///
    /// Receipts and invoices legitimately round: line items can sum to `12.499` against
    /// a printed `12.50`. A naïve `==` on ``Decimal`` therefore fails valid documents and
    /// sends the model into pointless repair loops. Prefer this helper in
    /// ``Extractable/validateInvariants()``.
    ///
    /// The tolerance is always the caller's choice; the default
    /// (``defaultMoneyTolerance`` / `0.01`) is a sensible starting point, not hidden magic.
    ///
    /// - Parameters:
    ///   - other: The amount to compare against.
    ///   - tolerance: Maximum absolute difference still considered equal.
    /// - Returns: `true` when `abs(self - other) <= tolerance`.
    public func isApproximatelyEqual(
        to other: Decimal,
        tolerance: Decimal = .defaultMoneyTolerance
    ) -> Bool {
        var difference = self - other
        if difference < 0 {
            difference = -difference
        }
        return difference <= tolerance
    }
}

/// Marks a type as extractable and synthesizes ``Extractable`` conformance,
/// a static ``extractionSchema``, and lenient `Codable` decoding.
@attached(
    member,
    names: named(CodingKeys), named(extractionSchema)
)
@attached(
    extension,
    conformances: Extractable, Codable, Sendable,
    names: named(init(from:)), named(encode(to:))
)
public macro Extractable() = #externalMacro(module: "ExtractMacros", type: "ExtractableMacro")

/// Attaches a natural-language extraction guide to a stored property.
///
/// The hint is embedded into ``ExtractionSchema`` and the extraction prompt.
@attached(peer)
public macro Guide(_ description: String) = #externalMacro(module: "ExtractMacros", type: "GuideMacro")
