import Foundation

/// A type that can be extracted from unstructured documents via an LLM.
///
/// Conformances are generated by the ``Extractable()`` macro. Do not implement
/// this protocol manually unless you need a hand-written schema.
public protocol Extractable: Codable, Sendable {
    /// JSON-Schema-like description of this type used for prompting and validation.
    nonisolated static var extractionSchema: ExtractionSchema { get }
}

/// Marks a type as extractable and synthesizes ``Extractable`` conformance,
/// a static ``extractionSchema``, and lenient `Codable` decoding.
@attached(
    member,
    names: named(CodingKeys), named(extractionSchema)
)
@attached(
    extension,
    conformances: Extractable, Codable, Sendable,
    names: named(init(from:)), named(encode(to:))
)
public macro Extractable() = #externalMacro(module: "ExtractMacros", type: "ExtractableMacro")

/// Attaches a natural-language extraction guide to a stored property.
///
/// The hint is embedded into ``ExtractionSchema`` and the extraction prompt.
@attached(peer)
public macro Guide(_ description: String) = #externalMacro(module: "ExtractMacros", type: "GuideMacro")
